all:
	@echo "Write this Makefile by your self."
.PHONY: sim
sim:
	$(call git_commit, "sim RTL") # DO NOT REMOVE THIS LINE!!!
	@echo "Write this Makefile by your self."
	@bash sim_test.sh

include ../Makefile
